version: "3.8"
services:
  stride1:
    image: stridezone:stride
    hostname: stride
    volumes:
      - ./scripts/state/stride1:/home/stride/.stride
    ports:
      - "26657:26657"
      - "1317:1317"
      - "9090:9090"

  stride2:
    image: stridezone:stride
    hostname: stride
    volumes:
      - ./scripts/state/stride2:/home/stride/.stride

  stride3:
    image: stridezone:stride
    hostname: stride
    volumes:
      - ./scripts/state/stride3:/home/stride/.stride

  gaia1:
    # image: stridezone/stride:latest
    image: stridezone:gaia
    hostname: stride
    volumes:
      - ./scripts/state/gaia1:/home/gaia/.gaia
    ports:
      - "26557:26657"
      - "1307:1317"
      - "9080:9090"
  gaia2:
    # image: stridezone/stride:latest
    image: stridezone:gaia
    hostname: stride
    volumes:
      - ./scripts/state/gaia2:/home/gaia/.gaia

  gaia3:
    # image: stridezone/stride:latest
    image: stridezone:gaia
    hostname: stride
    volumes:
      - ./scripts/state/gaia3:/home/gaia/.gaia

  hermes:
    image: stridezone:hermes
    volumes:
      - ~/.hermes:/home/hermes/.hermes
      - ./scripts/state/hermes/config.toml:/home/hermes/.hermes/config.toml
    restart: always

  relayer:
    image: stridezone:relayer
    volumes:
      - ./scripts/state/relayer:/home/relayer/.relayer
    restart: always

  icq:
    image: stridezone:interchain-queries
    volumes:
      - ./scripts/state/icq:/home/icq/.icq
    restart: always
