global:
  api-listen-addr: :5183
  timeout: 10s
  memo: ""
  light-cache-size: 20
chains:
  stride:
    type: cosmos
    value:
      key: rly1
      chain-id: STRIDE
      rpc-addr: http://stride1:26657
      account-prefix: stride
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02ustrd
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  gaia:
    type: cosmos
    value:
      key: rly2
      chain-id: GAIA
      rpc-addr: http://gaia1:26657
      account-prefix: cosmos
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uatom
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  juno:
    type: cosmos
    value:
      key: rly3
      chain-id: JUNO
      rpc-addr: http://juno1:26657
      account-prefix: juno
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02ujuno
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  osmo:
    type: cosmos
    value:
      key: rly4
      chain-id: OSMO
      rpc-addr: http://osmo1:26657
      account-prefix: osmo
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uosmo
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  stars:
    type: cosmos
    value:
      key: rly5
      chain-id: STARS
      rpc-addr: http://stars1:26657
      account-prefix: stars
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02ustars
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  host:
    type: cosmos
    value:
      key: rly6
      chain-id: HOST
      rpc-addr: http://host1:26657
      account-prefix: stride
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02uwalk
      coin-type: 118
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
  evmos:
    type: cosmos
    value:
      key: rly7
      chain-id: evmos_9001-2
      rpc-addr: http://evmos1:26657
      account-prefix: evmos
      keyring-backend: test
      gas-adjustment: 1.3
      gas-prices: 0.02aevmos
      coin-type: 60
      debug: false
      timeout: 20s
      output-format: json
      sign-mode: direct
      extra-codecs:
        - ethermint
  # {new-host-zone}:
  #   type: cosmos
  #   value:
  #     key: rly{N}
  #     chain-id: {CHAIN_ID}
  #     rpc-addr: http://{node_prefix}1:26657
  #     account-prefix: {bech32_hrp_account_prefix}
  #     keyring-backend: test
  #     gas-adjustment: 1.3
  #     gas-prices: 0.02{minimal_denom}
  #     coin-type: {coin-type}
  #     debug: false
  #     timeout: 20s
  #     output-format: json
  #     sign-mode: direct

paths:
  stride-gaia:
    src:
      chain-id: STRIDE
    dst:
      chain-id: GAIA
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-gaia-ics:
    src:
      chain-id: STRIDE
      client-id: 07-tendermint-1
    dst:
      chain-id: GAIA
      client-id: 07-tendermint-1
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-osmo:
    src:
      chain-id: STRIDE
    dst:
      chain-id: OSMO
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-juno:
    src:
      chain-id: STRIDE
    dst:
      chain-id: JUNO
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-stars:
    src:
      chain-id: STRIDE
    dst:
      chain-id: STARS
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-host:
    src:
      chain-id: STRIDE
    dst:
      chain-id: HOST
    src-channel-filter:
      rule: ""
      channel-list: []
  stride-evmos:
    src:
      chain-id: STRIDE
    dst:
      chain-id: evmos_9001-2
    src-channel-filter:
      rule: ""
      channel-list: []
  # stride-{new-host-zone}:
  #   src:
  #     chain-id: STRIDE
  #   dst:
  #     chain-id: {CHAIN_ID}
  #   src-channel-filter:
  #     rule: ""
  #     channel-list: []
